### ISSUE TITLE
Hunter: Do companion beasts scale too well?

### ISSUE THREAD

**Issue by orjanbp** [WC5E/Warcraft-5e-Conversion#258]
As a point of reference, a Dire Wolf has 37 HP (5d10 + 10) and a 14 AC.

By Hunter level 12, the same Dire Wolf would have reached 105 HP (14d10 + 28) and 18 AC (14 + 4).

This is effectively an extra member of the party, defensively. 

Is this too much, does the companion's HP scale too fast? 

Should its AC not be influenced, but rather stay as it is? 

We should check up on other criticisms leveraged against the UA Revised Ranger, from which this whole setup has been based, and see what other people have figured about this situation.

**Comment by orjanbp** [comment]
We could get some cues off of the newest Artificer revision here. Especially;

- Don't let the pet AC scale, but have it stay as it is with the pet initially.

- Adjust the HP scaling so that it peaks at ~100 HP at 20th level.

- With a "squishier" pet, allow the hunter to spend time during a (long?) rest to revive a dead pet.

- Maybe require the hunter to spend their bonus action to have the pet attack, and only allow the pet to take the *Dodge* action otherwise. Essentially folding the pet back into the hunter's direct action economy, but not have it as extreme as the pet requiring an action. 

    - That said, whichever way we choose to fold the hunter's pet in, we should consider how this pans out compared to a potential "Lone Wolf" feature for hunters not choosing to bring a pet.

    - Might be that, if the hunter requires a bonus action to have their pet attack, that a plausible trade-off could be simply allowing the Lone Wolf hunter to make one extra attack. The Lone Wolf hunter would have a higher damage potential, but most desirable hunter pets already average ~10-15 damage per turn and would provide the hunter with an extra HP buffer of at least half their own HP.

**Comment by Tyloris** [comment]
With the 3.0 Hunter revision, this is no longer an issue, as it uses a standardized statblock based on the Beasts of Land, Sky, and Sea from TCE. If the version from the 3.0 document proves to be a problem, that will be a separate issue (figuratively and literally).
