### ISSUE TITLE
Class: General class feedback

### ISSUE THREAD

**Issue by Jihia** [WC5E/Warcraft-5e-Conversion#541]
Silverblade compiled a large document filled with feedback for the reworked 3.0 classes, this is worth sifting through when we get around to working on version 3.1

[Silverblade's Feedback Document](https://docs.google.com/document/d/1Q45kb_U7L45j9j6oRFbXzGyz5hJvHvcXBd69veFi-tk/edit)

**Comment by orjanbp** [comment]
Closing this because it's a stale issue and the and the linked doc deleted
