### ISSUE TITLE
Hunter: Sorting out their "dead" levels.

### ISSUE THREAD

**Issue by Jihia** [WC5E/Warcraft-5e-Conversion#557]
The 3.0 rework of our Hunter class has a number of "dead" levels, where the class does not gain a feature and minimal (or no) increase somewhere else.
- 6th level: Hunter's Mark increases to 1d6
- 9th level: +1 focus die
- 13th level: +1 focus die
- 17th level: No features or increase in previous features.

**Comment by Tyloris** [comment]
Fixed in the latest hunter revision.
