### ISSUE TITLE
Discipline Priest: Penance balance

### ISSUE THREAD

**Issue by orjanbp** [WC5E/Warcraft-5e-Conversion#558]
Comment in on the 1st level Discipline priest Penance ability, from Reddit.

> Isn't the nerf to Discipline Priests a little severe?
> 
> Just talking about the 1st level stuff here, previously Discipline got to cast Spare the Dying as a bonus action at range, and any healing spells against unconscious creatures did maximum healing.
> 
> Now, whenever you heal, a creature makes a Wisdom save or they take half your level in Psychic damage. That's you using a spell slot to deal a maximum of 10 Psychic damage at twentieth level, after a Wisdom save. And you can only use it Cha mod times per rest. It's legitamitely so little damage that the time spent rolling isn't worth it. Shouldn't this just be automatic damage if it's so low and requires a spell slot?

I like the duality that Penance offers. It's a core Discipline ability as well, so it fits pretty solid where it is. 

But should we watch its space and consider if we should up it a bit? Penance as it's written in the 3.0 playtest (as of March 6th when writing this), is like this: 

**Penance**
> At 1st level, your can exert your will through your healing spells. Whenever you use a spell of 1st level or higher to restore hit points to a creature, you may choose a creature within 30 feet of it to succeed on a Wisdom saving throw, or take necrotic damage equal to half your priest level.
> You can use this feature a number of times equal to your Charisma modifier. You regain expended uses when you finish a short or long rest.

The "requires a spell slot" pointer feels misguided, since this is basically extra butter on top of your healing. You're not losing anything, just gaining a nice extra on top of the healing you're doing anyway. 

But we could consider upping the damage, maybe? Match your Priest level rather than it being half of it (since it is all or nothing)? 

We could make it so that you're dealing damage to a target for half of what the healing spell healed, but that would make it really powerful to just dip one level into Priest to grab Penance for any other healing build. If we did that, we should let the use limiter scale internally in the class rather than by CHA.

**Comment by OmNomDom308** [comment]
Feel this is a bit outdated with the newest priest document, could be good to resolve
