### ISSUE TITLE
Hunter: Should we add more Focus abilities?

### ISSUE THREAD

**Issue by Jihia** [WC5E/Warcraft-5e-Conversion#592]
The Hunter gains a total of 4 Focus abilities, 3 through the Focus feature and an additional 1 at 5th level unique to each subclass. Should we look into additional Focus abilities at later levels, flesh out the base class further by adding new ways of using focus dice at later levels?

**Comment by Tyloris** [comment]
Fixed in the latest hunter version. Focus abilities are now basically maneuvers, giving them a large number of potential abilities.
