### ISSUE TITLE
Priest: Power Word: Radiance's effect differs from WoW

### ISSUE THREAD

**Issue by Jihia** [WC5E/Warcraft-5e-Conversion#595]
It was pointed out that our Priest's Power Word: Radiance has an effect that is completely different from what it does in World of Warcraft. Should we look into changing how the Power Word functions to better mirror Warcraft? 
_**Ours:**_ Reaction to attempt a frighten on an attack creature.
_**WoW:**_ Heals 4 nearby injured allies.

Jih: Personally speaking i'd be more inclined to simply give it a new name than try to mirror what it does in Warcraft, its effect isn't well suited for how faith points is set up.

**Comment by Frogvall** [comment]
I concur about changing the name rather than the mechanic.

**Comment by OmNomDom308** [comment]
Radiance iirc was reworked into a Devotion for the 3.1 priest
