### ISSUE TITLE
Priest: Is Holy Nova a poor feature for a healing subclass?

### ISSUE THREAD

**Issue by Jihia** [WC5E/Warcraft-5e-Conversion#597]
Holy Priest's gain Holy Nova as a feature at 14th level, allowing them to deal a small amount of radiant damage when they are hit by a melee attack, as well as pushing back the attacker on a failed save. Should we look into replacing this with another supportive feature for a pure healing subclass? and potentially give Holy Nova to Discipline Priests?
Pognabros suggested looking into the Life Domain for 5e Clerics and their features for a potential replacement.

**Comment by Tseims** [comment]
I'm fine with removing Holy Nova as long as the replacement feature doesn't have to do with healing. Currently Holy Nova breaks the monotony of healing features nicely, which is something I wouldn't want to change too drastically

**Comment by OmNomDom308** [comment]
With 3.1 priest, moved Holy Nova to a spell
