### ISSUE TITLE
Priest/Paladin: Spelling Errors

### ISSUE THREAD

**Issue by AceAzzermeen** [WC5E/Warcraft-5e-Conversion#604]
Paladin
CD: Holy Shield is missing a "deal" (you may (deal) radiant damage to them)

Priest
Power Word Barrier is missing a "the" (expend 1 faith point to force (the) creature to reroll the attack)

**Comment by OmNomDom308** [comment]
Paladin wording seems to have already been updated in a previous commit, and the Faith point phrasing is moved out with the update to Priest with Devotion
