### ISSUE TITLE
Hunter: Adding the Dueling Fighting Style to their kit

### ISSUE THREAD

**Issue by Jihia** [WC5E/Warcraft-5e-Conversion#613]
We either missed or neglected the Dueling fighting style when we made our Hunter rework, it is present in the 5e Ranger and a nice alternative for those who want to one-hand weapons.

**Comment by Frogvall** [comment]
Iirc, we did leave it out on purpose, due to it being a trap more or less. The trap comes from the hunter being extremely bonus action starved already and the player would likely realize it too late.

With the current redesign in mind, we might be able to make it worthwhile again.
