### ISSUE TITLE
Priests: Are they too squishy?

### ISSUE THREAD

**Issue by Jihia** [WC5E/Warcraft-5e-Conversion#640]
Priests are not proficient in any armor, nor do they get any spell that increases their AC in a similar manner to _Mage Armor_. Should we look into implementing a small, either the _mage armor_ spell, an Inner Flame spell that does a similar thing, or an Unarmored Defense feature for all priests to get baseline?

**Comment by orjanbp** [comment]
This issue can be closed because it is part of the ongoing 3.1 Priest revision to present a Priest equivalent in the form of an *Inner Fire* feature.
