### ISSUE TITLE
Priest: General Feedback

### ISSUE THREAD

**Issue by Jihia** [WC5E/Warcraft-5e-Conversion#661]
Issue compiling feedback from Tangerine's form and Silverblade's feedback document.

- **Bonus Cantrip.**
Should Discipline priests gain a cantrip above Holy or Shadow? what warrants this cantrip? should we look into changing it to another minor bonus, perhaps proficiency in Insight.

- **Penance and Pain Suppression.**
It has been pointed out that the limitation and usage of these two abilities should be swapped, with Penance being more readily available to the Priest and Pain Suppression being a more limited resource. Should we look into changing this?

- **Castigation.**
Wording needs a bit of revising, so that it says spells of 1st level or higher.

- **Echoes of Life.**
The removal of Holy's 1st-level feature _Echoes of Life_ feels weird and puts the primarily healing focused subclass behind.

- **Holy Nova.**
Overall might be too powerful, need less consistent damage and a limited number of uses.

- **Legacy of the Void.**
"It is annoying to track", Legacy of the Void offers a minor damage buff at an ever-increasing DC that they have to pass. Keeping track of the DC is more troublesome than it is worth.

- **Surrender to Madness**
Should this also apply to cantrips (RAW it does). We should add a clause to the wording that says "This damage can't be reduced or prevented in any way"

**Comment by OmNomDom308** [comment]
Most of these issues were addressed or made out of date with the new 3.1 priest, probably good to close?
