### ISSUE TITLE
Mage Spell Feedback

### ISSUE THREAD

**Issue by AceAzzermeen** [WC5E/Warcraft-5e-Conversion#683]
Arcane Barrage: This seems quite weak for a 4th level spell, both in terms of absolute power and gimmick (two attacks, pushback). For comparison, a 4th level scorching ray does a total of 10d6 damage, while this does 8d6, but you can spread it around. Spell creation guidelines say a spell like this should be doing around 10d8 damage baseline. I think the benefit is pretty minor, and not worth much if any damage trade-off.
Suggestion: If you want to keep this as a single target nuke, I’d put the damage somewhere around 5d8 per bolt, which puts it right at the recommended ‘single target no ½ save’ level, or maybe 6d6 if you think that’s too high and scales too well. An interesting alternative would be creating more bolts on upcasting, sort of a super-magic missiles. This is a little tricky to balance, but if you keep each bolt at 6d6, and scale upwards every 2 weapons like spiritual weapon, the total damage is basically where it should be at each spell level, more or less. So that would read, “At Higher Levels: When you cast this spell using a spell slot 5th level of or higher, you create an additional bolt for every two slot levels above the 4th.” There’s some room to play here with the base damage and bolt scaling, to get things exactly where you want them. Either way, more damage is definitely appropriate.

Arcane Explosion: Also probably weak compared to fireball: same damage at base level, but smaller radius and point blank. It upcasts a little better, but I doubt that’s enough to balance it out.
Suggestion: I wouldn’t increase the damage, but I’d find some other way to buff the spell. Pushback, knockdown, selective targeting, slightly increased radius, something to give it some pizzazz.

Blast Wave: This isn’t at all like the Warcraft blast wave, which has always been a point-blank AoE with some kind of stun/incapacitate component. The spell is fine, but what you’ve written works better for a ‘Alextrasza’s Fury’ kind of thing, where the cone makes more sense.
Suggestion: I’d at least make it a point-blank AoE rather than a cone. I’d also maybe drop the damage a bit and add a stun/incapacitate for a round component on a failed save: it’s an 8th level spell, that seems appropriate.

Ice Block: Just as a note, ‘free action’ is both not a term in 5E, and not needed here since you are explicitly allowed to drop concentration at any time.

Ice Nova: For an 8th level spell, you could safely make this restrained rather than grappled, which IMO feels more appropriate. Getting out should use the ‘can use their action to make a Strength check against your spell save DC’ language that is predominant in other similar features and creatures. If you’re going to let them hit the ice, you need to provide an AC for it.
Suggestion: I’d write, “On a failed save, a creature takes 10d6 cold damage and is restrained by the expanding ice for 1 minute. On a successful save, it takes half as much damage and isn’t restrained. A restrained target can use its action to attempt to break free, making a Strength check against your spell save DC. On a success, the target escapes and is no longer restrained by the ice.”

Living Bomb: Again, ‘free action’ isn’t a term nor is it necessary, since dropping concentration can be done at any time. Also, the description could probably use an editing pass; there’s several fragments and other opportunities for writing improvements.

Pyroblast: Similar effects (e.g., fire elemental) don’t require a check to douse flames, and I’m not sure why a Dexterity check is appropriate here. Just someone sacrificing their action is enough. Also, 10d10 is actually low for a ‘single target save negates’ spell: you could bump the damage up a bit, to something around 13d10.
Suggestion: I’d rewrite it to be, “On a hit, the target takes 13d10 fire damage and ignites. Until a creature takes an action to douse the fire, the target takes an 1d10 fire damage at the start of each of its turns.”

**Comment by AceAzzermeen** [comment]
Flurry
Was: 1 missile for 1d8 cold damage, scaling missile amount.
Now: 3 missiles for 1d4 each, scaling amount of damage die.

Blizzard
Doesn't require your action to activate on consecutive turns any more. 
Damage from 3d6 + 1d6 per level to 3d10 + 1d10 per level.

Arcane Barrage
Was: 2 bolts for 4d6 each, scaling 1d6 per level.
Now: 3 bolts for 5d4 each, scaling 1 additional bolt per level.

Arcane Explosion
Added functionality:  can't take reactions until the start of its next turn

Blast Wave
Renamed to Alextrasza’s Fury to better represent spell behaviour.
Changed damage from 12d8 to 12d6.
Added functionality: stunned until the end of their next turn.

Ice Block
Wording.

Ice Nova
Wording and mechanical tweak. Identical behaviour.

Living Bomb
Wording.

Pyroblast
Damage form 10d10 to 13d10.
Removed saving throw.

**Comment by Frogvall** [comment]
I think it got lost in transition somewhere, but we should limit Flurry to semi short range to make it not be the objectively best cantrip. 20 or 30 ft.
