### ISSUE TITLE
Priest Spell Feedback

### ISSUE THREAD

**Issue by AceAzzermeen** [WC5E/Warcraft-5e-Conversion#685]
Angelic Feather: Dodge as a bonus action is REALLY strong, especially for a 1st level spell.
Suggestion: Remove Dodge. That makes it pretty comparable to expeditious retreat (shorter duration, but can affect an ally and also allows disengage).

Divine Star: This seems really weak; at this level you’d almost certainly do more damage and healing total with a mass healing word + cantrip.
Suggestion: I’d probably rewrite like, “Roll X. Enemies in the star’s path must make a Dexterity save or take radiant damage equal to the amount rolled, or half damage on a successful save. Allies in the star’s path regain hit points equal to half the amount rolled.” Then you just increase the amount rolled when upcast like usual. I could see X being 4d6, 5d6, or even 4d8 if you wanted to make it scale better; there’s arguments for all. Finally, since lines are pretty tough to get good use out of, I could also see increasing the line length to 60 feet, but it’s not something I feel strongly about.

Mind Flay: First, the damage is rather low; you’d almost certainly be better served by just casting hold person. Second, to me, this doesn’t really capture the feel of mind flay, which is shadow’s signature spell. I’d try to make it a true channeled spell, more like an improved witch bolt.
Suggestion: I’d rewrite this to be more like witch bolt: the disadvantage effect (which is cool) only lasts until your next turn, but on subsequent turns you can use your action to trigger the effect again. It probably reads: “The creature must make a Wisdom saving throw. On a failed save, the target takes X psychic damage and has disadvantage on all attack rolls and ability checks until the end of your next turn. On a successful save, the target takes half damage and suffers no other effects. On each of your turns for the duration, you can use your action to force the creature to make a new Wisdom saving throw and repeat the spell’s effects, rolling damage again. The spell ends if you use your action to do anything else. The spell also ends if the target is ever outside the spell’s range or if it has total cover from you.” Need to clean up the repeating part in the middle, but something like that to me is a more faithful implementation of mind flay. Then I’d play with X, somewhere in the 2d6-3d6-2d8 range, to taste.

Shadow Crash: This is a fine spell, but the name doesn’t match the description, and the description doesn’t really match the Warcraft inspiration. I’d rewrite the description, personally (preferably in a way that better justifies a Constitution save, as well).
Suggestion: Here’s one option: “You hurl a heavy bolt of shadow energy to a point you choose within range, where it expands into a huge void of corrosive blackness.”

**Comment by AceAzzermeen** [comment]
This still needs to be addressed but the spells aren't in the priest document itself any more, so this doesn't need to happen to finalize the priest document.

**Comment by OmNomDom308** [comment]
I used this issue primarily when writing them the priest rework, so all of these points have been addressed with the current versions. This issue can be closed with the PR
