### ISSUE TITLE
Warlock: Diabloism cantrip

### ISSUE THREAD

**Issue by orjanbp** [WC5E/Warcraft-5e-Conversion#713]
This is an issue created to track feedback for the Diablosim cantrip. Since the material in question is currently in playtest, we can use this space to gather any findings and then make a decision at a future point. 

> The signature cantrips like diabolism--prestidigitation, thaumaturgy, etc.--are strong in versatility, but not absolute effect. And indeed, that should describe cantrips in general. Diabolism, on the other hand, has some rather powerful, ill-defined effects. 
> The first effect, for example, can effectively act as a mini-pass without trace for an entire group, by giving disadvantage on perception checks because of dim light or darkness. The second effect of causing rot, by virtue of having few limitations or specifications (unlimited size, for example), and being able to affect a creature's equipment, can be used to great potency. 
> And finally, the third effect of reanimating a tiny or small CR 0 creature, is both potent and underwritten. Mechanically, there's a lot missing. Does it use the same stats? Is it intelligent? Can you reanimate the same creature at the end of the duration? Are there creature type limitations on what can be reanimated? And so on. There's a reason animate dead has a pretty lengthy spell description--there's just a lot of details that need to be specified. More importantly, I think the power level of this effect is inappropriate for a cantrip. Animating the dead is a potent ability, and being able to (potentially) indefinitely animate a gnome commoner (for example) is, IMO, well beyond what a cantrip should be capable of. 
> I think that would be true even if you can't reanimate the same creature more than once. It's not necessarily a very powerful effect, especially depending on how some of the above questions gets clarified, but I believe it's nonetheless beyond the power of a cantrip. In whole, while I appreciate wanting to make an 'evil prestidigitation' for warlocks and other dark spellcasters, I think this cantrip needs revision, or to be removed altogether.

**Comment by Tyloris** [comment]
Updated the cantrip with some balance changes to fix the broken aspects.

**Comment by Tyloris** [comment]
There are a couple errors in how range is handled in the cantrip. Cantrip should read as thus:
> #### Diabolism
*Necromancy cantrip*
___
- **Casting Time:** 1 action
- **Range:** Up to 30 feet
- **Components:** S
- **Duration:** Up to 1 hour
___
This spell channels a small amount of dark energy. You create one of the following magical effects:
- Choose a point within 30 feet. In a 5-foot radius of that point, bright light becomes dim light, and dim light becomes darkness for 1 hour. Any light sources within the area have the light they produce suppressed for the duration.
- An object up to 1 cubic foot in size or an area up to 1 square foot that you touch lightly decays. Wood rots, glass cracks, flowers wilt. Casting the spell and then continuing to touch the target advances the decay; after 1 minute, the target is destroyed. This spell cannot affect creatures, magical objects, or sturdy materials like metal and stone.
- You can reanimate a Tiny 0 CR beast you touch for 1 hour. It is undead and obeys all of your commands to the best of its abilities, though it cannot attack. You cannot use this effect again until the reanimated creature dies, or the effect ends.
- You instantaneously light a candle, torch, or small campfire within 30 feet. The fire glows your choice of a smoldering red, bright green, or shadowy purple until extinguished. 
- Your fingertip glows green or purple for up to 1 minute. While it glows, you can use your finger to draw glowing lines of the same color on a solid surface that last for 1 hour.

If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.

Changes:
- Changed base range from Self to Up to 30 feet.
- Removed the words "within range" from the first line.
- Added the words "you touch" to the reanimation effect.
- Added a 30 foot range increment to the fire effect, matching the shadow effect's range.

**Comment by Tyloris** [comment]
No negative reviews so far, can be considered closed.
