### ISSUE TITLE
Referenceing Tasha's content.

### ISSUE THREAD

**Issue by AceAzzermeen** [WC5E/Warcraft-5e-Conversion#744]
Should we replace the two Metamagic options from Tasha's that are currently included in the mage document with a note block referring to the book instead. Possibly also referring to Sorcerous Versatility and or Cantrip Formulas?

I believe it was a mistake by me to just "reprint" them.

**Comment by OmNomDom308** [comment]
Yeah Id have to agree with that. Could get us in trouble a bit since we are technically reprinting something not in the SRD

**Comment by Tyloris** [comment]
The metamagic options that are OGL are Careful, Distant, Empowered, Extended, Heightened, Quickened, Subtle, and Twinned. All others that aren't homebrew need to be removed.

**Comment by AceAzzermeen** [comment]
I'm going to open a pull request replacing them with this note then. 

![grafik](https://user-images.githubusercontent.com/10117187/114466346-a94c4d00-9be8-11eb-8568-3dafcc76a84b.png)
```
> #### Optional Class Features
> See Tasha's Cauldron of Everything, Pg. 65 for additional Metamagic options. 
>
> You may also use the Sorcerous Versatility feature found on the same page or Cantrip Formulas from the Wizard class on Pg. 75.
```
