### ISSUE TITLE
Rogue: Outlaw feature "Tricks of the Trade" allows redirecting the attack back to the attacker by RAW

### ISSUE THREAD

**Issue by Maia-Everett** [WC5E/Warcraft-5e-Conversion#748]
I don't know if this is intended. Here is how Tricks of the Trade is worded:

> Beginning at 13th level, you can sometimes cause another creature to suffer an attack meant for you. When you are targeted by an attack while within 5 feet of a creature, you can use your reaction to have the attack target that creature instead of you.

By RAW, this allows redirecting the attack back to the attacker. If it's intentional, that's fine by me. If not, I suggest the following wording change:

> Beginning at 13th level, you can sometimes cause another creature to suffer an attack meant for you. When you are targeted by an attack while within 5 feet of a creature other than the attacker, you can use your reaction to have the attack target that creature instead of you.

**Comment by Frogvall** [comment]
I think this one slipped through. I think we should make the change as suggested.
