### ISSUE TITLE
Worgen: Keen Senses?

### ISSUE THREAD

**Issue by Tyloris** [WC5E/Warcraft-5e-Conversion#765]
Should we add a Keen Hearing and Smell trait to the worgen race, to match that of the monster?

Keen Hearing and Smell: You have advantage on Wisdom (Perception) checks that rely on hearing or smell.

**Comment by MagusRogue** [comment]
Not so much for hearings but definitely for smell

**Comment by Tyloris** [comment]
The worgen monster, as well as every wolf and wolf-based monster, has keen hearing and smell. If we're matching the monster top the PC race, it'd have to be both.

**Comment by MagusRogue** [comment]
That's fair then!

**Comment by Tyloris** [comment]
Current github races document has this trait.
