### ISSUE TITLE
CR calculator enhancements

### ISSUE THREAD

**Issue by AceAzzermeen** [WC5E/Warcraft-5e-Conversion#773]
When you press enter while inside a text field of the damage calculator the entire array is reset.

Support for formulas in the text fields. Example: 20+10.
Reason for this is to more easily see what the the on turn or off turn damage components are.
Examples: 
-On turn multi attack with multiple attacks. 
-Off turn for legendary actions and thorn (elemental body) like effects.
-Also when hp consist of actual hp and temp hp or arcane ward like effects.

For thorn like effects i could imagine adding an extra field like for regenerations could work, too.

**Comment by Tyloris** [comment]
Auv has his own github for the calculator: https://github.com/Frogvall/wc5e-cr-calculator
